### ISSUE TITLE
Unable to create the stack with  nap-autoscale-ubuntu-dev.yaml template

### ISSUE THREAD

**Issue by sshajiya** [f5devcentral/aws-waf-solution-template#30] opened 2021-12-15 14:54 UTC
While creating the stack with nap-autoscale-ubuntu-dev.yaml template through git hub actions or through manual, the stack is getting failed due to below issue.

Attaching the error snap for reference!!
![image](https://user-images.githubusercontent.com/39581520/146209055-882425f5-5056-4c70-b4bc-537b3eb48f48.png)

**Comment by 464d41** [comment] 2021-12-16 21:46
Thanks for reporting the issue. Please try to find the root cause and post it here. It will help a lot to speed up a resolution.

**Comment by sshajiya** [comment] 2021-12-17 03:03
![image](https://user-images.githubusercontent.com/39581520/146482218-641c9a3f-d39e-4040-b8fb-6c796411e154.png)

**Comment by yoctoalex** [comment] 2021-12-25 00:43
fixed and merged

**Closed by yoctoalex** 2021-12-25 00:43 UTC
Labels: bug
